<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><title>Microsoft Office HTML Example</title>
<style>

@page {
  size: A4 landscape;
  overflow:hidden;
}
@media print {
  html, body {
    width: 297mm;
    height: 210mm;
  }
  /* ... the rest of the rules ... */
}

#contenedor {
    width: 297mm;
    height: 210mm;
    padding:0mm;
    border:solid 3px blue;
    overflow: hidden;
  }

</style>
</head>
<body>

<div id="contenedor">

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu commodo sem. Aenean quis turpis fringilla, dignissim massa ut, euismod elit. Pellentesque elit augue, tempor convallis faucibus elementum, finibus nec orci. Morbi vitae egestas lorem. Etiam vitae arcu et nibh porta laoreet et eu ligula. Pellentesque in gravida tellus, ac fringilla est. Donec sagittis dolor tristique metus mattis, nec bibendum magna tempus. Nunc viverra id urna vel lacinia. Nulla semper felis quis ante lobortis interdum. Pellentesque ut laoreet nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse ac augue in diam congue molestie id vitae tellus. Cras quam nisi, congue at nunc at, dictum vestibulum lacus.

Aenean vitae consectetur ex, a scelerisque leo. Aenean in vulputate diam, eget fringilla odio. In mollis accumsan mi tincidunt vulputate. Vestibulum hendrerit, nibh vel euismod pretium, diam est elementum risus, porta mollis eros nibh nec sapien. Vestibulum rutrum ligula et nisl dictum, sed dapibus erat luctus. Pellentesque lacinia justo ut urna maximus vehicula. Aliquam euismod dignissim leo quis sagittis. Etiam interdum dui eu ipsum blandit, tristique sagittis massa aliquet. Duis eget enim nibh. Aenean ut ornare sapien, ac ornare justo. Integer faucibus sit amet elit vel consequat. Mauris orci mauris, sodales nec nulla sodales, sollicitudin suscipit mi.

Proin magna ex, fermentum nec tempus vel, euismod sit amet ante. Aliquam lacinia nulla eget purus vehicula accumsan. Nam sit amet purus sem. Integer eget mollis est. Phasellus sagittis nec nisl in sollicitudin. Curabitur dignissim tellus at imperdiet eleifend. Cras varius efficitur augue, sed rhoncus neque dictum id.

Nullam eu dui libero. Sed ac pretium lorem, vel egestas lacus. Duis dignissim, metus nec hendrerit ultricies, ligula lorem dapibus purus, id tempus dui risus eget mauris. Sed pretium, libero sit amet varius congue, mi risus posuere orci, et facilisis enim ligula non quam. Suspendisse potenti. Quisque neque est, gravida et risus id, vehicula rhoncus elit. Sed facilisis ipsum ac varius dapibus. Nullam auctor tortor tincidunt lorem interdum, eu efficitur quam varius. Vestibulum eu augue vel turpis rutrum tincidunt sed non quam. Nullam et tellus id nibh vehicula commodo vitae a sapien. Fusce consectetur enim id aliquam egestas. Cras congue odio metus, ac scelerisque arcu semper vitae. Maecenas id euismod felis.

Duis pulvinar lobortis lectus, ac accumsan augue consectetur nec. Sed egestas ipsum in ligula vehicula dictum. Praesent vulputate elit nunc, id porttitor magna elementum vitae. Pellentesque vitae auctor eros. Cras ultricies, eros sed suscipit efficitur, ante ipsum ultricies lectus, at bibendum justo ante non tortor. Etiam sit amet pharetra mi, sed egestas erat. Nullam eleifend velit nisl, a semper nisi tempor et. Maecenas laoreet neque ut posuere porttitor. Nulla ultrices odio eu ex ultricies, vitae tristique arcu faucibus. Nulla commodo, nisl sed scelerisque imperdiet, libero ante auctor turpis, ac gravida dui elit id lacus. Nunc aliquet neque diam, quis vestibulum metus ultricies non. Aliquam facilisis leo at nulla vestibulum, vel euismod neque elementum. Integer porttitor tincidunt nunc id commodo. Morbi elementum, lectus eget malesuada condimentum, nisi mi facilisis metus, a rutrum ex arcu et eros. Mauris accumsan, mauris et gravida vehicula, turpis orci porttitor nibh, eget interdum enim lacus ut lacus.

Maecenas sed erat mollis, interdum lorem vitae, accumsan ligula. Duis ultricies risus sapien, vel pellentesque ligula vulputate sed. Proin a dictum nunc. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Vivamus mollis diam euismod augue venenatis, vitae dignissim nisl aliquam. Nam eget viverra tellus. Duis ut ornare elit. Donec id aliquet ipsum.

Suspendisse congue venenatis augue, quis auctor urna cursus in. Vivamus et orci a erat faucibus vestibulum a fermentum diam. Vestibulum condimentum nisi id mi eleifend efficitur. Nam eu ligula nisi. Praesent mollis et nisi nec semper. Phasellus finibus justo id ante eleifend, et rutrum libero interdum. Integer arcu purus, eleifend id cursus non, tempus eget ante. Donec pulvinar mi eu ligula accumsan tincidunt. Suspendisse potenti. Ut et tellus vel magna finibus posuere et id urna.

Donec ultrices ornare suscipit. Aliquam tincidunt arcu quis magna egestas, varius posuere justo viverra. Aenean sollicitudin est eu neque semper, ac vestibulum risus viverra. In sollicitudin nisi id odio luctus, at commodo risus tristique. Vestibulum non eros at tortor vestibulum hendrerit. Nulla malesuada leo tincidunt eros laoreet, sit amet vehicula elit ornare. Donec dignissim mauris nec dolor blandit lacinia et id lectus. Sed tincidunt dapibus turpis, vel gravida diam molestie vitae. Proin feugiat, sapien non mattis congue, lacus lacus sagittis tellus, vitae vehicula nibh nunc eget enim.

Vestibulum augue nulla, iaculis vel nibh a, fringilla sollicitudin lorem. Pellentesque a nisi vel odio sagittis iaculis et non dolor. Sed et pretium diam. Suspendisse faucibus ex mauris, id vehicula urna facilisis in. Quisque in nulla a nulla placerat gravida. Integer vestibulum tortor eu ante tincidunt, ut dignissim lectus interdum. Praesent ac justo non urna luctus vulputate. Etiam turpis augue, bibendum a risus eget, sollicitudin consequat nulla. Mauris commodo neque id arcu facilisis, id semper justo dignissim. Integer gravida nunc eget nisi condimentum feugiat. Suspendisse efficitur mi dui, ac ornare purus lobortis in. Quisque sit amet pellentesque odio.

Nulla facilisi. Aliquam tincidunt, augue ac imperdiet consequat, urna justo molestie arcu, ut feugiat justo mi sit amet dolor. Etiam tempor ut nibh eget fermentum. Vestibulum in arcu laoreet, pharetra dolor et, consectetur risus. Nullam accumsan non massa a rutrum. Donec luctus sed nisi id congue. Maecenas ex nisl, auctor accumsan turpis et, semper interdum turpis. Mauris tempor tempor enim. Maecenas eget tincidunt purus, sit amet pulvinar tortor. Maecenas consequat, quam egestas semper eleifend, nulla risus elementum ligula, et varius lacus ipsum eget erat. Quisque tristique turpis eu mi aliquet ullamcorper. Sed in fermentum tellus. Curabitur posuere, eros a sodales tempor, quam justo vulputate ipsum, quis sagittis turpis velit non massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sagittis elit eros, eget consectetur magna porttitor eu. Curabitur sagittis libero convallis finibus interdum.

Pellentesque porttitor nibh ligula, non aliquam nisi scelerisque dictum. Integer pellentesque consequat urna nec consectetur. Sed mollis luctus diam vehicula maximus. Etiam tristique, nisl nec faucibus convallis, ex nisl interdum eros, vel iaculis ligula risus eget eros. Quisque et vulputate libero, ac rhoncus purus. Aenean venenatis nisi eget risus semper, vitae porta enim condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse rutrum vitae ante nec feugiat. Ut non sapien elit. Vestibulum sollicitudin ante eget placerat aliquam. Pellentesque ultrices, tellus ac tempus volutpat, nisi justo tincidunt nibh, vitae euismod erat risus quis enim. Donec quis ipsum urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce a urna facilisis, rhoncus leo et, pretium risus. Integer molestie congue pellentesque.

Nam scelerisque dui eu euismod luctus. Sed vitae maximus turpis. Praesent eleifend ultrices lacus, ac varius neque aliquet non. Sed et eleifend purus. Nunc sollicitudin urna non varius cursus. Etiam eget libero non dui volutpat rutrum. Morbi pulvinar ut arcu id tempor. Sed interdum vel risus sit amet rutrum. Vestibulum elit felis, posuere eu felis eget, tempor tincidunt dolor. Praesent laoreet est et feugiat posuere. Proin scelerisque tellus vitae eros convallis lacinia. Pellentesque dapibus ex vel tempus euismod.

Quisque ac est tempor magna scelerisque venenatis at eu tortor. Etiam sed eros eros. Nullam egestas, est ut maximus fringilla, nunc odio iaculis justo, nec tempus nisl arcu et tortor. Praesent facilisis rhoncus efficitur. Nullam quis enim sed dolor tincidunt elementum. Aliquam tincidunt efficitur orci, vel accumsan dolor luctus sit amet. Aenean eu neque id est mollis pulvinar.

Integer orci justo, fermentum ut ultrices eu, suscipit ut libero. Proin ac massa elementum enim sollicitudin vestibulum. Suspendisse aliquam blandit turpis, a tincidunt nibh vehicula vel. Sed a orci scelerisque, euismod sem vel, viverra ligula. Nunc mattis diam ut massa lacinia lobortis. Aliquam tristique justo a quam volutpat, vel rhoncus arcu consequat. Praesent interdum nec sem eget euismod. Sed aliquam diam nec turpis pellentesque aliquet. Vestibulum vestibulum et nisl cursus auctor. Maecenas vitae lacus dolor. Integer vitae blandit massa, eget varius odio. Pellentesque rutrum, eros eget egestas dignissim, diam elit pharetra nisl, id auctor justo quam non metus. Sed aliquet posuere dolor, vitae maximus arcu mattis eu.

Etiam viverra placerat tincidunt. Mauris eget gravida ex. Vestibulum nec cursus enim, at lacinia libero. Ut ut tempus urna, sit amet ullamcorper nunc. Maecenas laoreet enim non massa porttitor, eget malesuada nisl semper. Integer sed tortor a libero maximus vulputate. Pellentesque tincidunt enim in metus vehicula, et feugiat purus efficitur. Phasellus facilisis tempus nibh, in ultricies dui mollis nec. 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu commodo sem. Aenean quis turpis fringilla, dignissim massa ut, euismod elit. Pellentesque elit augue, tempor convallis faucibus elementum, finibus nec orci. Morbi vitae egestas lorem. Etiam vitae arcu et nibh porta laoreet et eu ligula. Pellentesque in gravida tellus, ac fringilla est. Donec sagittis dolor tristique metus mattis, nec bibendum magna tempus. Nunc viverra id urna vel lacinia. Nulla semper felis quis ante lobortis interdum. Pellentesque ut laoreet nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse ac augue in diam congue molestie id vitae tellus. Cras quam nisi, congue at nunc at, dictum vestibulum lacus.

Aenean vitae consectetur ex, a scelerisque leo. Aenean in vulputate diam, eget fringilla odio. In mollis accumsan mi tincidunt vulputate. Vestibulum hendrerit, nibh vel euismod pretium, diam est elementum risus, porta mollis eros nibh nec sapien. Vestibulum rutrum ligula et nisl dictum, sed dapibus erat luctus. Pellentesque lacinia justo ut urna maximus vehicula. Aliquam euismod dignissim leo quis sagittis. Etiam interdum dui eu ipsum blandit, tristique sagittis massa aliquet. Duis eget enim nibh. Aenean ut ornare sapien, ac ornare justo. Integer faucibus sit amet elit vel consequat. Mauris orci mauris, sodales nec nulla sodales, sollicitudin suscipit mi.

Proin magna ex, fermentum nec tempus vel, euismod sit amet ante. Aliquam lacinia nulla eget purus vehicula accumsan. Nam sit amet purus sem. Integer eget mollis est. Phasellus sagittis nec nisl in sollicitudin. Curabitur dignissim tellus at imperdiet eleifend. Cras varius efficitur augue, sed rhoncus neque dictum id.

Nullam eu dui libero. Sed ac pretium lorem, vel egestas lacus. Duis dignissim, metus nec hendrerit ultricies, ligula lorem dapibus purus, id tempus dui risus eget mauris. Sed pretium, libero sit amet varius congue, mi risus posuere orci, et facilisis enim ligula non quam. Suspendisse potenti. Quisque neque est, gravida et risus id, vehicula rhoncus elit. Sed facilisis ipsum ac varius dapibus. Nullam auctor tortor tincidunt lorem interdum, eu efficitur quam varius. Vestibulum eu augue vel turpis rutrum tincidunt sed non quam. Nullam et tellus id nibh vehicula commodo vitae a sapien. Fusce consectetur enim id aliquam egestas. Cras congue odio metus, ac scelerisque arcu semper vitae. Maecenas id euismod felis.

Duis pulvinar lobortis lectus, ac accumsan augue consectetur nec. Sed egestas ipsum in ligula vehicula dictum. Praesent vulputate elit nunc, id porttitor magna elementum vitae. Pellentesque vitae auctor eros. Cras ultricies, eros sed suscipit efficitur, ante ipsum ultricies lectus, at bibendum justo ante non tortor. Etiam sit amet pharetra mi, sed egestas erat. Nullam eleifend velit nisl, a semper nisi tempor et. Maecenas laoreet neque ut posuere porttitor. Nulla ultrices odio eu ex ultricies, vitae tristique arcu faucibus. Nulla commodo, nisl sed scelerisque imperdiet, libero ante auctor turpis, ac gravida dui elit id lacus. Nunc aliquet neque diam, quis vestibulum metus ultricies non. Aliquam facilisis leo at nulla vestibulum, vel euismod neque elementum. Integer porttitor tincidunt nunc id commodo. Morbi elementum, lectus eget malesuada condimentum, nisi mi facilisis metus, a rutrum ex arcu et eros. Mauris accumsan, mauris et gravida vehicula, turpis orci porttitor nibh, eget interdum enim lacus ut lacus.

Maecenas sed erat mollis, interdum lorem vitae, accumsan ligula. Duis ultricies risus sapien, vel pellentesque ligula vulputate sed. Proin a dictum nunc. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Vivamus mollis diam euismod augue venenatis, vitae dignissim nisl aliquam. Nam eget viverra tellus. Duis ut ornare elit. Donec id aliquet ipsum.

Suspendisse congue venenatis augue, quis auctor urna cursus in. Vivamus et orci a erat faucibus vestibulum a fermentum diam. Vestibulum condimentum nisi id mi eleifend efficitur. Nam eu ligula nisi. Praesent mollis et nisi nec semper. Phasellus finibus justo id ante eleifend, et rutrum libero interdum. Integer arcu purus, eleifend id cursus non, tempus eget ante. Donec pulvinar mi eu ligula accumsan tincidunt. Suspendisse potenti. Ut et tellus vel magna finibus posuere et id urna.

Donec ultrices ornare suscipit. Aliquam tincidunt arcu quis magna egestas, varius posuere justo viverra. Aenean sollicitudin est eu neque semper, ac vestibulum risus viverra. In sollicitudin nisi id odio luctus, at commodo risus tristique. Vestibulum non eros at tortor vestibulum hendrerit. Nulla malesuada leo tincidunt eros laoreet, sit amet vehicula elit ornare. Donec dignissim mauris nec dolor blandit lacinia et id lectus. Sed tincidunt dapibus turpis, vel gravida diam molestie vitae. Proin feugiat, sapien non mattis congue, lacus lacus sagittis tellus, vitae vehicula nibh nunc eget enim.

Vestibulum augue nulla, iaculis vel nibh a, fringilla sollicitudin lorem. Pellentesque a nisi vel odio sagittis iaculis et non dolor. Sed et pretium diam. Suspendisse faucibus ex mauris, id vehicula urna facilisis in. Quisque in nulla a nulla placerat gravida. Integer vestibulum tortor eu ante tincidunt, ut dignissim lectus interdum. Praesent ac justo non urna luctus vulputate. Etiam turpis augue, bibendum a risus eget, sollicitudin consequat nulla. Mauris commodo neque id arcu facilisis, id semper justo dignissim. Integer gravida nunc eget nisi condimentum feugiat. Suspendisse efficitur mi dui, ac ornare purus lobortis in. Quisque sit amet pellentesque odio.

Nulla facilisi. Aliquam tincidunt, augue ac imperdiet consequat, urna justo molestie arcu, ut feugiat justo mi sit amet dolor. Etiam tempor ut nibh eget fermentum. Vestibulum in arcu laoreet, pharetra dolor et, consectetur risus. Nullam accumsan non massa a rutrum. Donec luctus sed nisi id congue. Maecenas ex nisl, auctor accumsan turpis et, semper interdum turpis. Mauris tempor tempor enim. Maecenas eget tincidunt purus, sit amet pulvinar tortor. Maecenas consequat, quam egestas semper eleifend, nulla risus elementum ligula, et varius lacus ipsum eget erat. Quisque tristique turpis eu mi aliquet ullamcorper. Sed in fermentum tellus. Curabitur posuere, eros a sodales tempor, quam justo vulputate ipsum, quis sagittis turpis velit non massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sagittis elit eros, eget consectetur magna porttitor eu. Curabitur sagittis libero convallis finibus interdum.

Pellentesque porttitor nibh ligula, non aliquam nisi scelerisque dictum. Integer pellentesque consequat urna nec consectetur. Sed mollis luctus diam vehicula maximus. Etiam tristique, nisl nec faucibus convallis, ex nisl interdum eros, vel iaculis ligula risus eget eros. Quisque et vulputate libero, ac rhoncus purus. Aenean venenatis nisi eget risus semper, vitae porta enim condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse rutrum vitae ante nec feugiat. Ut non sapien elit. Vestibulum sollicitudin ante eget placerat aliquam. Pellentesque ultrices, tellus ac tempus volutpat, nisi justo tincidunt nibh, vitae euismod erat risus quis enim. Donec quis ipsum urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce a urna facilisis, rhoncus leo et, pretium risus. Integer molestie congue pellentesque.

Nam scelerisque dui eu euismod luctus. Sed vitae maximus turpis. Praesent eleifend ultrices lacus, ac varius neque aliquet non. Sed et eleifend purus. Nunc sollicitudin urna non varius cursus. Etiam eget libero non dui volutpat rutrum. Morbi pulvinar ut arcu id tempor. Sed interdum vel risus sit amet rutrum. Vestibulum elit felis, posuere eu felis eget, tempor tincidunt dolor. Praesent laoreet est et feugiat posuere. Proin scelerisque tellus vitae eros convallis lacinia. Pellentesque dapibus ex vel tempus euismod.

Quisque ac est tempor magna scelerisque venenatis at eu tortor. Etiam sed eros eros. Nullam egestas, est ut maximus fringilla, nunc odio iaculis justo, nec tempus nisl arcu et tortor. Praesent facilisis rhoncus efficitur. Nullam quis enim sed dolor tincidunt elementum. Aliquam tincidunt efficitur orci, vel accumsan dolor luctus sit amet. Aenean eu neque id est mollis pulvinar.

Integer orci justo, fermentum ut ultrices eu, suscipit ut libero. Proin ac massa elementum enim sollicitudin vestibulum. Suspendisse aliquam blandit turpis, a tincidunt nibh vehicula vel. Sed a orci scelerisque, euismod sem vel, viverra ligula. Nunc mattis diam ut massa lacinia lobortis. Aliquam tristique justo a quam volutpat, vel rhoncus arcu consequat. Praesent interdum nec sem eget euismod. Sed aliquam diam nec turpis pellentesque aliquet. Vestibulum vestibulum et nisl cursus auctor. Maecenas vitae lacus dolor. Integer vitae blandit massa, eget varius odio. Pellentesque rutrum, eros eget egestas dignissim, diam elit pharetra nisl, id auctor justo quam non metus. Sed aliquet posuere dolor, vitae maximus arcu mattis eu.

Etiam viverra placerat tincidunt. Mauris eget gravida ex. Vestibulum nec cursus enim, at lacinia libero. Ut ut tempus urna, sit amet ullamcorper nunc. Maecenas laoreet enim non massa porttitor, eget malesuada nisl semper. Integer sed tortor a libero maximus vulputate. Pellentesque tincidunt enim in metus vehicula, et feugiat purus efficitur. Phasellus facilisis tempus nibh, in ultricies dui mollis nec. 

</div>


</body>
</html>